defaults: &defaults
  adapter: postgresql
  template: template0
  host: localhost

development:
  <<: *defaults
  database: socialnet_development

test:
  <<: *defaults
  min_message: warning
  database: share_test